#!/usr/bin/env python3
"""
Organizze to Beancount Importer v5

Orquestrador que coordena os handlers especializados.

Regras de importação:
a) Despesa: D sem R pareado → Expense+ / Asset-
b) Receita: R sem D pareado → Asset+ / Income-
c) Transferência: D + R pareado por valor (±1 dia) → Asset- / Asset+
d) Pagamento cartão: D com Categoria="Outros" + descrição com "pagamento/fatura" → Liabilities:+ / Asset:-
"""

import logging
from pathlib import Path

import pandas as pd

import card_payments_handler
import expenses_handler
import incomes_handler
import transfers_handler
from organizze_shared import (
    extract_accounts_from_df,
    extract_categories_from_df,
    sanitize_description,
    sanitize_name,
)


logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def generate_accounts_file(
    bank_accounts: set,
    credit_cards: set,
    expense_categories: set,
    income_categories: set,
    ledger_dir: Path,
) -> None:
    """Gera arquivo de contas Beancount."""
    expense_categories = expense_categories | {"SaquesATM", "Boletos", "OutrosCartao"}
    income_categories = income_categories | {"TransferenciasRecebidas"}

    lines = [
        "; Accounts Beancount - Auto-generated by organizze_v5.py",
        "; DO NOT EDIT MANUALLY",
        "",
        '2018-01-01 open Equity:SaldoInicial BRL "STRICT"',
        '2018-01-01 open Equity:TransferenciasPendentes BRL "STRICT"',
        '2018-01-01 open Equity:Ajustes BRL "STRICT"',
        "",
    ]
    for acc in sorted(bank_accounts):
        lines.append(f'2018-01-01 open Assets:BR:{acc} BRL "STRICT"')
    lines.append("")
    for acc in sorted(credit_cards):
        lines.append(f'2018-01-01 open Liabilities:Cartao:{acc} BRL "STRICT"')
    lines.append("")
    for exp in sorted(expense_categories):
        lines.append(f'2018-01-01 open Expenses:{exp} BRL "STRICT"')
    lines.append("")
    for inc in sorted(income_categories):
        lines.append(f'2018-01-01 open Income:{inc} BRL "STRICT"')

    with open(ledger_dir / "accounts.beancount", "w") as f:
        f.write("\n".join(lines))


def generate_saldo_inicial_entries(df: pd.DataFrame) -> tuple[list[str], int]:
    """Gera entradas para saldos iniciais."""
    lines = []
    count = 0

    for idx, row in df.iterrows():
        if row["D/R"] != "D":
            continue

        desc = sanitize_description(row.get("Descrição", ""))
        if "saldo inicial" not in desc.lower():
            continue

        date = row["Data"].strftime("%Y-%m-%d")
        value = abs(row["Valor"])
        conta = row.get("CONTA", "")
        status = row.get("Situação", "Pago")
        flag = "*" if status == "Pago" else "!"

        from organizze_shared import get_account_path

        debit = get_account_path(conta)

        lines.append(f'{date} {flag} "{desc}"')
        lines.append(f"  {debit:40s} {value:>10.2f} BRL")
        lines.append(f"  Equity:SaldoInicial {-value:>10.2f} BRL")
        lines.append('  origem_id: "saldo_inicial"')
        lines.append("")
        count += 1

    return lines, count


def main():
    project_dir = Path(__file__).parent.parent
    data_dir = project_dir / "data"
    ledger_dir = project_dir / "ledger"

    input_file = data_dir / "unificado_dr_ordenado.xlsx"
    if not input_file.exists():
        logger.error(f"Arquivo não encontrado: {input_file}")
        return

    logger.info("Iniciando importação Organizze -> Beancount v5")

    df = pd.read_excel(input_file)
    df["Data"] = pd.to_datetime(df["Data"])
    df = df.sort_values(["Data", "Valor"]).reset_index(drop=True)

    logger.info(f"Total de lançamentos: {len(df)}")

    bank_accounts, credit_cards = extract_accounts_from_df(df)
    logger.info(f"Contas: {len(bank_accounts)} bancárias, {len(credit_cards)} cartões")

    pagto_cartao_indices = card_payments_handler.identify_card_payment_indices(df)
    cartao_expense_indices = expenses_handler.identify_cartao_expense_indices(df)
    saque_indices = expenses_handler.identify_saque_indices(df)
    boleto_indices = expenses_handler.identify_boleto_indices(df)
    transferencia_recebida_indices = (
        incomes_handler.identify_transferencia_recebida_indices(df)
    )
    ajuste_indices = incomes_handler.identify_ajuste_indices(df)

    excluded_indices = (
        pagto_cartao_indices
        | cartao_expense_indices
        | saque_indices
        | boleto_indices
        | transferencia_recebida_indices
        | ajuste_indices
    )

    processed_transfers, orphans = transfers_handler.identify_transfers(
        df, excluded_indices
    )
    excluded_indices |= processed_transfers

    expense_categories, income_categories = extract_categories_from_df(df)
    generate_accounts_file(
        bank_accounts,
        credit_cards,
        expense_categories,
        income_categories,
        ledger_dir,
    )

    logger.info("Gerando lançamentos...")

    lines = [
        "; History Beancount - Auto-generated by organizze_v5.py",
        "; DO NOT EDIT MANUALLY",
        "",
    ]

    total_count = 0

    transfer_lines, transfer_count = transfers_handler.generate_transfer_entries(
        df, processed_transfers
    )
    lines.extend(transfer_lines)
    total_count += transfer_count

    orphan_lines, orphan_count = transfers_handler.generate_orphan_transfer_entries(
        orphans, df
    )
    lines.extend(orphan_lines)
    total_count += orphan_count

    pagto_lines, pagto_count = card_payments_handler.generate_card_payment_entries(
        df, pagto_cartao_indices
    )
    lines.extend(pagto_lines)
    total_count += pagto_count

    cartao_expense_lines, cartao_expense_count = (
        expenses_handler.generate_cartao_expense_entries(df, cartao_expense_indices)
    )
    lines.extend(cartao_expense_lines)
    total_count += cartao_expense_count

    saque_lines, saque_count = expenses_handler.generate_saque_entries(
        df, saque_indices
    )
    lines.extend(saque_lines)
    total_count += saque_count

    boleto_lines, boleto_count = expenses_handler.generate_boleto_entries(
        df, boleto_indices
    )
    lines.extend(boleto_lines)
    total_count += boleto_count

    transferencia_lines, transferencia_count = (
        incomes_handler.generate_transferencia_recebida_entries(
            df, transferencia_recebida_indices
        )
    )
    lines.extend(transferencia_lines)
    total_count += transferencia_count

    ajuste_lines, ajuste_count = incomes_handler.generate_ajuste_entries(
        df, ajuste_indices
    )
    lines.extend(ajuste_lines)
    total_count += ajuste_count

    saldo_inicial_lines, saldo_inicial_count = generate_saldo_inicial_entries(df)
    lines.extend(saldo_inicial_lines)
    total_count += saldo_inicial_count

    expense_lines, expense_count = expenses_handler.generate_expense_entries(
        df, excluded_indices
    )
    lines.extend(expense_lines)
    total_count += expense_count

    income_lines, income_count = incomes_handler.generate_income_entries(
        df, excluded_indices
    )
    lines.extend(income_lines)
    total_count += income_count

    with open(ledger_dir / "history.beancount", "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Total de lançamentos: {total_count}")
    logger.info("Concluído! Execute: bean-check ledger/main.beancount")


if __name__ == "__main__":
    main()
